Finished hw3

diff --git a/hw3/durm b/hw3/durm
--- a/hw3/durm
+++ b/hw3/durm
@@ -1,5 +1,17 @@
-#!/bin/bash -x
+#!/bin/bash 
 
-du -a trashcan/ | awk -F ' ' ' {sum += $1;} END {print sum;} '
+# Checks if trashbin exists
+if [[ -d "~/trashbin" ]]; then
+	echo "Error: Trashbin does not exist. Please call 'srm' first before calling any other 'rm' functions."
+	exit 1
+fi
+
+# Checks if trashbin is empty
+if [[ -z "~/trashbin/trash_content" ]]; then
+	echo "Error: Trashbin is empty."
+	exit 1
+fi
+
+du -a ~/trashbin/trash_content | awk -F ' ' ' {sum += $1;} END {print sum;} '
 
 
diff --git a/hw3/lsrm b/hw3/lsrm
--- a/hw3/lsrm
+++ b/hw3/lsrm
@@ -1,3 +1,15 @@
-#!/bin/bash -x
+#!/bin/bash 
 
-ls -l trashcan/
+# Checks if trashbin exists
+if [[ -d "~/trashbin" ]]; then
+	echo "Error: Trashbin does not exist. Please call 'srm' first before calling any other 'rm' functions."
+	exit 1
+fi
+
+# Checks if trashbin is empty
+if [[ -z "~/trashbin/trash_content" ]]; then
+	echo "Error: Trashbin is empty."
+	exit 1
+fi
+
+ls -lRA ~/trashbin/trash_content
diff --git a/hw3/lss b/hw3/lss
--- a/hw3/lss
+++ b/hw3/lss
@@ -1,32 +1,36 @@
-#!/bin/bash -x
+#!/bin/bash 
 
 # If no arguments, print hw2-lss and exit
 if [ "$#" -eq 0 ]; then
 	ls -lS
-	exit 0
+	exit 1
 fi
 
 for arg in "$@";
 do
 	if [[ $arg == -* ]]; then
 		if [[ $arg == *g* ]]; then
+			echo "Error: Option -g not allowed."
 			echo "Option -g makes it so that owner is not listed, which is an unnecessary feature for lss."
-			exit 0
+			exit 1
 		fi
 
-		if [[ $arg == *G* ]]; then
+		if [[ $arg == *G* || $arg == *no-group* ]]; then
+			echo "Error: Option -G not allowed."
 			echo "Option -G makes it so that group is not listed, which is an unnecessary feature for lss."
-			exit 0
+			exit 1
 		fi
 
-		if [[ $arg == *i* ]]; then
+		if [[ $arg == *i* || $arg == *inode* ]]; then
+			echo "Error: Option -i not allowed."
 			echo "Option -i (prints out the inode number for each file) messes up the sorting by Size in descending order."
-			exit 0
+			exit 1
 		fi
 
-		if [[ $arg == *s* ]]; then
+		if [[ $arg == *s* || $arg == *size* ]]; then
+			echo "Error: Option -s not allowed."
 			echo "Option -s (prints out the size allocated for each file) messes up the sorting by size in descending order."
-			exit 0
+			exit 1
 		fi
 	fi
 done
@@ -35,4 +39,4 @@ done
 # -i (--inode) - print index num of each file
 # -g - like -l but do not list owner
 
-exec ls -lS "$@"
+exec ls -lSd "$@"
diff --git a/hw3/srm b/hw3/srm
--- a/hw3/srm
+++ b/hw3/srm
@@ -1,10 +1,49 @@
-#!/bin/bash -x
+#!/bin/bash
+
+# Check if no arg
+if [[ "$#" -eq 0 ]]; then
+	echo "Error: No arguments."
+	exit 1
+fi
+
+# Create the trashbin directory if it does not exist
+mkdir -p ~/trashbin
+mkdir -p ~/trashbin/trash_content
+touch ~/trashbin/trashlog
 
 for arg in "$@"
 do
+	FILEPATH=""
 
-#remember the log the original directory
+	# Checks if the argument is . or .. (obviously don't want that happening)
+	if [[ $arg == "." ]] || [[ $arg == ".." ]]; then
+		echo "Error: Attempted to srm current/parent directory."
+		exit 1
+	fi
 
-mv -f $arg ./trashcan/
+	# Checking if the argument is an absolute filepath or a relative filepath
+	if [[ $arg == ~* ]] || [[ $arg == /* ]]; then
+		echo "Note: You entered the absolute filepath."
+	else
+		echo "Note: You entered the relative filepath."
+		FILEPATH=$(pwd)
+		FILEPATH+="/"
+	fi 
 
+	# Getting the Absolute Path to the argument
+	DIRNAME="$(dirname $arg)/"
+	FILENAME=$(basename $arg)
+	FILEPATH+=$DIRNAME
+	DEST=~/trashbin/trash_content/"$FILENAME"
+	echo "Moving $FILEPATH$FILENAME to the trashbin."
+
+	# If the file to be srm'd is a file put -f as the second column of the log
+	# If it is a directory put -d
+	if [[ -d $arg ]]; then
+		echo "$FILENAME -d $FILEPATH" >> ~/trashbin/trashlog
+#		mv -f $arg $DEST
+	else
+		echo "$FILENAME -f $FILEPATH" >> ~/trashbin/trashlog
+	fi
+	mv -f "$arg" "$DEST"
 done
